spec:
  template:
    spec:
      containers:
      - name: fraud-api
        volumeMounts:
        - name: fraud-script
          mountPath: /app/app.py
          subPath: app.py
      volumes:
      - name: fraud-script
        configMap:
          name: fraud-api-script
