apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fraud-detection-system.fullname" . }}-kafka
  labels:
    {{- include "fraud-detection-system.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.kafka.replicas }}
  selector:
    matchLabels:
      app: {{ include "fraud-detection-system.fullname" . }}-kafka
  template:
    metadata:
      labels:
        app: {{ include "fraud-detection-system.fullname" . }}-kafka
    spec:
      nodeSelector:
        node-type: infra
      containers:
        - name: kafka
          image: "{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.kafka.ports.containerPort }}
          env:
            - name: KAFKA_BROKER_ID
              value: "{{ .Values.kafka.env.KAFKA_BROKER_ID }}"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "{{ include "fraud-detection-system.fullname" . }}-zookeeper:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://{{ include "fraud-detection-system.fullname" . }}-kafka:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "{{ .Values.kafka.env.KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR }}"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "{{ .Values.kafka.env.KAFKA_TRANSACTION_STATE_LOG_MIN_ISR }}"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "{{ .Values.kafka.env.KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR }}"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "{{ .Values.kafka.env.KAFKA_AUTO_CREATE_TOPICS_ENABLE }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fraud-detection-system.fullname" . }}-kafka
  labels:
    {{- include "fraud-detection-system.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: plaintext
  selector:
    app: {{ include "fraud-detection-system.fullname" . }}-kafka
