apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fraud-detection-system.fullname" . }}-grafana
  labels:
    {{- include "fraud-detection-system.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "fraud-detection-system.fullname" . }}-grafana
  template:
    metadata:
      labels:
        app: {{ include "fraud-detection-system.fullname" . }}-grafana
    spec:
      nodeSelector:
        node-type: infra
      containers:
        - name: grafana
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "{{ .Values.grafana.env.GF_SECURITY_ADMIN_USER }}"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "{{ .Values.grafana.env.GF_SECURITY_ADMIN_PASSWORD }}"
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "{{ .Values.grafana.env.GF_USERS_ALLOW_SIGN_UP }}"
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
            - name: provisioning-config
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yml
              subPath: dashboards.yml
            - name: provisioning-config
              mountPath: /etc/grafana/provisioning/datasources/datasources.yml
              subPath: datasources.yml
            - name: dashboards-config
              mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: grafana-data
          emptyDir: {}
        - name: provisioning-config
          configMap:
            name: {{ include "fraud-detection-system.fullname" . }}-grafana-provisioning
        - name: dashboards-config
          configMap:
            name: {{ include "fraud-detection-system.fullname" . }}-grafana-dashboards
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fraud-detection-system.fullname" . }}-grafana
  labels:
    {{- include "fraud-detection-system.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: {{ include "fraud-detection-system.fullname" . }}-grafana
